// SPDX-License-Identifier: Apache-2.0
//
// Copyright (C) 2026 Nero Duality, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include "nfc_ccid_frame.h"
#include "nfc_pcsc_contactless.h"

#include <stdint.h>

#if defined(NERO_CCID_USB_BUILD)

enum {
  RDR_PC_DATABLOCK = (uint8_t)NFC_CCID_MSG_RDR_TO_PC_DATABLOCK,
  RDR_PC_SLOTSTATUS = (uint8_t)NFC_CCID_MSG_RDR_TO_PC_SLOTSTATUS,
  RDR_PC_PARAMETERS = (uint8_t)NFC_CCID_MSG_RDR_TO_PC_PARAMETERS,
  RDR_PC_ESCAPE = (uint8_t)NFC_CCID_MSG_RDR_TO_PC_ESCAPE,
  RDR_PC_DATA_RATE_AND_CLOCK =
      (uint8_t)NFC_CCID_MSG_RDR_TO_PC_DATA_RATE_AND_CLOCK,

  CCID_PC_SLOT_STATUS = (uint8_t)NFC_CCID_MSG_PC_TO_RDR_SLOTSTATUS,
  CCID_PC_ICC_ON = (uint8_t)NFC_CCID_MSG_PC_TO_RDR_ICC_POWER_ON,
  CCID_PC_ICC_OFF = (uint8_t)NFC_CCID_MSG_PC_TO_RDR_ICC_POWER_OFF,
  CCID_PC_XFR = (uint8_t)NFC_CCID_MSG_PC_TO_RDR_XFR,
  CCID_PC_GET_PARAMS = (uint8_t)NFC_CCID_MSG_PC_TO_RDR_GET_PARAMETERS,
  CCID_PC_RESET_PARAMS = (uint8_t)NFC_CCID_MSG_PC_TO_RDR_RESET_PARAMETERS,
  CCID_PC_SET_PARAMS = (uint8_t)NFC_CCID_MSG_PC_TO_RDR_SET_PARAMETERS,
  CCID_PC_ESCAPE = (uint8_t)NFC_CCID_MSG_PC_TO_RDR_ESCAPE,
  CCID_PC_ABORT = (uint8_t)NFC_CCID_MSG_PC_TO_RDR_ABORT,
  CCID_PC_ICC_CLOCK = (uint8_t)NFC_CCID_MSG_PC_TO_RDR_ICC_CLOCK,
  CCID_PC_T0_APDU = (uint8_t)NFC_CCID_MSG_PC_TO_RDR_T0_APDU,
  CCID_PC_SECURE = (uint8_t)NFC_CCID_MSG_PC_TO_RDR_SECURE,
  CCID_PC_MECHANICAL = (uint8_t)NFC_CCID_MSG_PC_TO_RDR_MECHANICAL,
  CCID_PC_SET_RATE_CLOCK =
      (uint8_t)NFC_CCID_MSG_PC_TO_RDR_SET_DATA_RATE_AND_CLOCK,

  CCID_XFR_LEVEL_SINGLE = (uint8_t)NFC_CCID_XFR_LEVEL_SINGLE,
  CCID_XFR_LEVEL_CHAIN_BEGIN = (uint8_t)NFC_CCID_XFR_LEVEL_CHAIN_BEGIN,
  CCID_XFR_LEVEL_CHAIN_END = (uint8_t)NFC_CCID_XFR_LEVEL_CHAIN_END,
  CCID_XFR_LEVEL_CHAIN_MIDDLE = (uint8_t)NFC_CCID_XFR_LEVEL_CHAIN_MIDDLE,
  CCID_XFR_LEVEL_RESPONSE_CONTINUE = (uint8_t)NFC_CCID_XFR_RESPONSE_CONTINUE,

  CCICC_ACTIVE = (uint8_t)NFC_CCID_ICC_ACTIVE,
  CCICC_INACTIVE = (uint8_t)NFC_CCID_ICC_INACTIVE,
  CCICC_NO_ICC = (uint8_t)NFC_CCID_ICC_NO_ICC,
  CCICC_CMD_FAIL = (uint8_t)NFC_CCID_ICC_CMD_FAIL,
  CCICC_CMD_TIME_EXTENSION = (uint8_t)NFC_CCID_ICC_CMD_TIME_EXTENSION,
  CCICC_TIME_EXTENSION_BWT_MULTIPLIER =
      (uint8_t)NFC_CCID_TIME_EXTENSION_BWT_MULTIPLIER,
  CCID_ERR_CMD_ABORTED = (uint8_t)0xFF,
  CCID_ERR_ICC_MUTE = (uint8_t)0xFE,
  CCID_ERR_BAD_DWLENGTH = (uint8_t)0x01,
  CCID_ERR_SLOT_DOES_NOT_EXIST = (uint8_t)0x05,
  CCID_ERR_POWER_SELECT_UNSUPPORTED = (uint8_t)0x07,
  CCID_ERR_BAD_LEVEL_PARAMETER = (uint8_t)0x08,
  CCID_ERR_PARAMS_PROTOCOL_TYPE = (uint8_t)0x09,

  CCID_PROTOCOL_NUM_T0 = (uint8_t)NFC_PCSC_PROTOCOL_T0,
  CCID_PROTOCOL_NUM_T1 = (uint8_t)NFC_PCSC_PROTOCOL_T1,
};

#endif /* NERO_CCID_USB_BUILD */
