# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2026 Nero Duality, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Wire the kit-generated OpenSSF hardening dials into the firmware (Arduino) build.
#
# cmake/Hardening.flags.by-<compile_db slug>.mk are generated by `make lint`
# (openssf job) from .github/lint-c-cpp.yaml policy.overrides.openssf-hardening —
# do not hand-edit them. Each provides NERO_OPENSSF_C/CXX/CPPFLAGS already dialed
# for that target's compile DB (host-only flags removed for the MCU cross-build).
#
# Select exactly one fragment for $(TARGET)+$(FIRMWARE_PRODUCT)+$(NFC_USB_MODE).
# Paths must appear literally here: hardeninglint scans Makefile/make/*.mk for each
# by_compile_db slug and rejects a single variable-expanded include.
#
# The lint matrix has one profile for every valid board/product/USB build.

NERO_OPENSSF_CFLAGS :=
NERO_OPENSSF_CXXFLAGS :=
NERO_OPENSSF_CPPFLAGS :=
NERO_OPENSSF_SELECTED_PROFILES :=

# FIRMWARE_PRODUCT defaults to nfc for legacy `make nfc`; product aliases set it.
FIRMWARE_PRODUCT ?= nfc

ifeq ($(TARGET),arduino_uno_r4wifi)
ifeq ($(NFC_USB_MODE),ccid)
NERO_OPENSSF_SELECTED_PROFILES += arduino_uno_r4wifi/reader/ccid
-include $(CURDIR)/cmake/Hardening.flags.by-build__lint__firmware__arduino_uno_r4wifi__reader__ccid__compile_commands_json.mk
else ifeq ($(FIRMWARE_PRODUCT),reader)
NERO_OPENSSF_SELECTED_PROFILES += arduino_uno_r4wifi/reader/cdc
-include $(CURDIR)/cmake/Hardening.flags.by-build__lint__firmware__arduino_uno_r4wifi__reader__cdc__compile_commands_json.mk
else ifeq ($(FIRMWARE_PRODUCT),writer)
NERO_OPENSSF_SELECTED_PROFILES += arduino_uno_r4wifi/writer/cdc
-include $(CURDIR)/cmake/Hardening.flags.by-build__lint__firmware__arduino_uno_r4wifi__writer__cdc__compile_commands_json.mk
else ifeq ($(FIRMWARE_PRODUCT),nfc)
NERO_OPENSSF_SELECTED_PROFILES += arduino_uno_r4wifi/nfc/cdc
-include $(CURDIR)/cmake/Hardening.flags.by-build__lint__firmware__arduino_uno_r4wifi__nfc__cdc__compile_commands_json.mk
endif
endif

ifeq ($(TARGET),nucleo_wba65ri)
ifeq ($(NFC_USB_MODE),ccid)
NERO_OPENSSF_SELECTED_PROFILES += nucleo_wba65ri/reader/ccid
-include $(CURDIR)/cmake/Hardening.flags.by-build__lint__firmware__nucleo_wba65ri__reader__ccid__compile_commands_json.mk
else ifeq ($(FIRMWARE_PRODUCT),reader)
NERO_OPENSSF_SELECTED_PROFILES += nucleo_wba65ri/reader/cdc
-include $(CURDIR)/cmake/Hardening.flags.by-build__lint__firmware__nucleo_wba65ri__reader__cdc__compile_commands_json.mk
else ifeq ($(FIRMWARE_PRODUCT),writer)
NERO_OPENSSF_SELECTED_PROFILES += nucleo_wba65ri/writer/cdc
-include $(CURDIR)/cmake/Hardening.flags.by-build__lint__firmware__nucleo_wba65ri__writer__cdc__compile_commands_json.mk
else ifeq ($(FIRMWARE_PRODUCT),nfc)
NERO_OPENSSF_SELECTED_PROFILES += nucleo_wba65ri/nfc/cdc
-include $(CURDIR)/cmake/Hardening.flags.by-build__lint__firmware__nucleo_wba65ri__nfc__cdc__compile_commands_json.mk
endif
endif
